import os

SECRET_KEY = 'cambodiakingdomofwonder$12312$2'

#KREDIT
#FACEBOOK_TOKEN="EAADNf4VUX4kBAO8hFPMYZAz5PfcYedzEvullF9ZC2QGc6VZAT7s1PIRQ72VnQydZBZCam4ZB3CQfxArZCLqpzOcnsgjUFSj2RZABGXBlethm1pWg69E8usmdybF5D3LlyP2CZCw87FJxU6OAUZB5vxqtVcxxlHZBZCW38sZAhuMWNAPGZCnAZDZD"
#VERIFY_TOKEN="KRD4@team"

#EBOT
#FACEBOOK_TOKEN="EAAG8ZCCEzUlEBACgYnoDTeqp93mlTihOe60ie0Ul8zdxey1ZAyumIqiJjrriByN4uRICo6Ppo8FZCVelWIYGMHkcf1fqeucwfDUyRLyrF6ZC4QihdxZC0WdzEZBAedpCkJ6TEXYs29JOc8FNjcOOS6Dtmi4GJUZCJtLJrNmPgYvPwZDZD"
#VERIFY_TOKEN="ebot messenger$$"

#B702
FACEBOOK_TOKEN="EAACYXHj78jcBAJPBcjovYJMUuaZCrwWEvAj6hQimwn6ExSIlT3JX5kvTMYaNyEOA1DLnurJar8s8Y5eqVSc6MnEHPq8PfED5VaZCZCNo2jZBuSdvdgSY5QYVeMNZBBqb1nRg8TZC1XTKyviW9FE2cVaobKB8LkPkyXz4cP2pT0EAZDZD"
VERIFY_TOKEN="B702"

CASA_LINK = ""

#SET ENV VARIABLE TO FEED ORACLE DATABASE
os.environ["NLS_LANG"] = "AMERICAN.AL32UTF8"

#DATABASE CONNECTION
SQLALCHEMY_DATABASE_URI='oracle://app:Ms#S3cure2018@192.168.2.12:1521/KRDDEV'
#SQLALCHEMY_DATABASE_URI='oracle://app:devNdeploy.3@192.168.1.53:1525/KINHOUSE'
SQLALCHEMY_DATABASE_ECHO=False
SQLALCHEMY_DATABASE_ENCODING='utf-8'
SQLALCHEMY_DATABASE_CONVERT_UNICODE=True
SQLALCHEMY_DATABASE_ECHO_POOL=True
SQLALCHEMY_DATABASE_POOL_SIZE=100
SQLALCHEMY_DATABASE_POOL_TIMEOUT=30
SQLALCHEMY_DATABASE_MAX_OVERFLOW=-1
SQLLACHEMY_DATABASE_POOL_RECYCLE=-1

#DAILOGFLOW
DIALOGFLOW_PROJECT_ID="bankingbot-48180"